---
- name: Setup system and users
  ansible.builtin.import_tasks: system.yml

- name: Configure security (SSH, UFW, Fail2Ban)
  ansible.builtin.import_tasks: security.yml

- name: Install Docker
  ansible.builtin.import_tasks: docker.yml

- name: Deploy Selenium Grid
  ansible.builtin.import_tasks: selenium.yml
