---
- name: Create project directory
  ansible.builtin.file:
    path: "{{ selenium_grid_project_path }}"
    state: directory
    owner: "{{ selenium_grid_deploy_user }}"
    group: "{{ selenium_grid_deploy_user }}"
    mode: '0755'

- name: Generate htpasswd hash for basic auth
  ansible.builtin.shell: >
    htpasswd -nb {{ basic_user }} '{{ basic_password }}' | sed -e 's/\$/$$/g'
  register: htpasswd_hash
  changed_when: false
  no_log: true

- name: Copy Grid configuration
  ansible.builtin.copy:
    src: selenium_grid_4/
    dest: "{{ selenium_grid_project_path }}/"
    owner: "{{ selenium_grid_deploy_user }}"
    group: "{{ selenium_grid_deploy_user }}"

- name: Ensure proper ownership of project directory
  ansible.builtin.file:
    path: "{{ selenium_grid_project_path }}"
    owner: "{{ selenium_grid_deploy_user }}"
    group: "{{ selenium_grid_deploy_user }}"
    recurse: yes

- name: Template .env file
  ansible.builtin.template:
    src: env.j2
    dest: "{{ selenium_grid_project_path }}/.env"
    owner: "{{ selenium_grid_deploy_user }}"
    group: "{{ selenium_grid_deploy_user }}"
    mode: '0600'

- name: Start Docker Compose services
  ansible.builtin.shell: docker compose -f docker-compose.yml up -d
  args:
    chdir: "{{ selenium_grid_project_path }}"
  ignore_errors: yes
