---
- name: Copy Grid configuration
  ansible.builtin.copy:
    src: selenium_grid_4/
    dest: "{{ selenium_grid_project_path }}/"
    owner: "{{ selenium_grid_deploy_user }}"
    group: "{{ selenium_grid_deploy_user }}"

- name: Ensure proper ownership of project directory
  ansible.builtin.file:
    path: "{{ selenium_grid_project_path }}"
    owner: "{{ selenium_grid_deploy_user }}"
    group: "{{ selenium_grid_deploy_user }}"
    recurse: yes

- name: Restart Docker Compose services
  ansible.builtin.shell: docker compose -f docker-compose.yml up -d --force-recreate
  args:
    chdir: "{{ selenium_grid_project_path }}"
