---
- name: Initialize and secure VDS
  hosts: all
  become: yes

  vars_prompt:
    - name: basic_user
      prompt: "Enter Basic Auth Username for Selenium Grid"
      default: "admin"
      private: no

    - name: basic_password
      prompt: "Enter Basic Auth Password"
      private: yes

    - name: domain_name
      prompt: "Enter Domain Name (e.g. selenium.my-domain.com)"
      private: no

    - name: acme_email
      prompt: "Enter Email for Let's Encrypt SSL"
      private: no

  roles:
    - selenium_grid
