# configs mapping browser capabilities to specific stable images
configs = [
  "selenium/standalone-chrome:4.20.0", '{"browserName": "chrome"}',
  "selenium/standalone-firefox:4.20.0", '{"browserName": "firefox"}'
]

url = "unix:///var/run/docker.sock"
# url = "npipe:////./pipe/docker_engine"

[node]
max-sessions = 4