version: '3.8'

services:
  traefik:
    image: traefik:v3.1
    container_name: traefik
    command:
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    restart: unless-stopped
    networks:
      - grid_network

  selenium-hub:
    image: selenium/hub:4.20.0
    container_name: selenium-hub
    environment:
      - SE_EVENT_BUS_THREADS=16
    ports:
      - "4444:4444" 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.selenium.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.selenium.entrypoints=websecure"
      - "traefik.http.routers.selenium.tls.certresolver=myresolver"
      - "traefik.http.services.selenium.loadbalancer.server.port=4444"
      
      - "traefik.http.routers.selenium.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=${BASIC_AUTH_HASH}"
    restart: unless-stopped
    networks:
      - grid_network

  node-docker:
    image: selenium/node-docker:4.20.0
    container_name: node-docker
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_DOCKER_CONFIG_FILENAME=config.toml
    volumes:
      - ./config.toml:/opt/selenium/config.toml:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./assets:/opt/selenium/assets
    restart: unless-stopped
    networks:
      - grid_network

networks:
  grid_network:
    driver: bridge